#!/usr/bin/env bash
#
# dmenu_unicode_math.sh

set -euo pipefail

command -v dmenu >/dev/null 2>&1 || {
    echo "Error: dmenu is not installed." >&2
    exit 1
}

# symbol<TAB>hex<TAB>name
entries=$(cat <<'EOF'
∀   (U+2200)  FOR ALL
∁   (U+2201)  COMPLEMENT
∂   (U+2202)  PARTIAL DIFFERENTIAL
∃   (U+2203)  THERE EXISTS
∄   (U+2204)  THERE DOES NOT EXIST
∅   (U+2205)  EMPTY SET
∆   (U+2206)  INCREMENT
∇   (U+2207)  NABLA
∈   (U+2208)  ELEMENT OF
∉   (U+2209)  NOT AN ELEMENT OF
∊   (U+220A)  SMALL ELEMENT OF
∋   (U+220B)  CONTAINS AS MEMBER
∌   (U+220C)  DOES NOT CONTAIN AS MEMBER
∍   (U+220D)  SMALL CONTAINS AS MEMBER
∎   (U+220E)  END OF PROOF
∏   (U+220F)  N-ARY PRODUCT
∐   (U+2210)  N-ARY COPRODUCT
∑   (U+2211)  N-ARY SUMMATION
−   (U+2212)  MINUS SIGN
∓   (U+2213)  MINUS-OR-PLUS SIGN
∔   (U+2214)  DOT PLUS
∕   (U+2215)  DIVISION SLASH
∖   (U+2216)  SET MINUS
∗   (U+2217)  ASTERISK OPERATOR
∘   (U+2218)  RING OPERATOR
∙   (U+2219)  BULLET OPERATOR
√   (U+221A)  SQUARE ROOT
∛   (U+221B)  CUBE ROOT
∜   (U+221C)  FOURTH ROOT
∝   (U+221D)  PROPORTIONAL TO
∞   (U+221E)  INFINITY
∟   (U+221F)  RIGHT ANGLE
∠   (U+2220)  ANGLE
∡   (U+2221)  MEASURED ANGLE
∢   (U+2222)  SPHERICAL ANGLE
∣   (U+2223)  DIVIDES
∤   (U+2224)  DOES NOT DIVIDE
∥   (U+2225)  PARALLEL TO
∦   (U+2226)  NOT PARALLEL TO
∧   (U+2227)  LOGICAL AND
∨   (U+2228)  LOGICAL OR
∩   (U+2229)  INTERSECTION
∪   (U+222A)  UNION
∫   (U+222B)  INTEGRAL
∬   (U+222C)  DOUBLE INTEGRAL
∭   (U+222D)  TRIPLE INTEGRAL
∮   (U+222E)  CONTOUR INTEGRAL
∯   (U+222F)  SURFACE INTEGRAL
∰   (U+2230)  VOLUME INTEGRAL
∱   (U+2231)  CLOCKWISE INTEGRAL
∲   (U+2232)  CLOCKWISE CONTOUR INTEGRAL
∳   (U+2233)  ANTICLOCKWISE CONTOUR INTEGRAL
∴   (U+2234)  THEREFORE
∵   (U+2235)  BECAUSE
∶   (U+2236)  RATIO
∷   (U+2237)  PROPORTION
∸   (U+2238)  DOT MINUS
∹   (U+2239)  EXCESS
∺   (U+223A)  GEOMETRIC PROPORTION
∻   (U+223B)  HOMOTHETIC
∼   (U+223C)  TILDE OPERATOR
∽   (U+223D)  REVERSED TILDE
∾   (U+223E)  INVERTED LAZY S
∿   (U+223F)  SINE WAVE
≀   (U+2240)  WREATH PRODUCT
≁   (U+2241)  NOT TILDE
≂   (U+2242)  MINUS TILDE
≃   (U+2243)  ASYMPTOTICALLY EQUAL TO
≄   (U+2244)  NOT ASYMPTOTICALLY EQUAL TO
≅   (U+2245)  APPROXIMATELY EQUAL TO
≆   (U+2246)  APPROXIMATELY BUT NOT ACTUALLY EQUAL TO
≇   (U+2247)  NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO
≈   (U+2248)  ALMOST EQUAL TO
≉   (U+2249)  NOT ALMOST EQUAL TO
≊   (U+224A)  ALMOST EQUAL OR EQUAL TO
≋   (U+224B)  TRIPLE TILDE
≌   (U+224C)  ALL EQUAL TO
≍   (U+224D)  EQUIVALENT TO
≎   (U+224E)  GEOMETRICALLY EQUIVALENT TO
≏   (U+224F)  DIFFERENCE BETWEEN
≐   (U+2250)  APPROACHES THE LIMIT
≑   (U+2251)  GEOMETRICALLY EQUAL TO
≒   (U+2252)  APPROXIMATELY EQUAL TO OR THE IMAGE OF
≓   (U+2253)  IMAGE OF OR APPROXIMATELY EQUAL TO
≔   (U+2254)  COLON EQUALS
≕   (U+2255)  EQUALS COLON
≖   (U+2256)  RING IN EQUAL TO
≗   (U+2257)  RING EQUAL TO
≘   (U+2258)  CORRESPONDS TO
≙   (U+2259)  ESTIMATES
≚   (U+225A)  EQUIANGULAR TO
≛   (U+225B)  STAR EQUALS
≜   (U+225C)  DELTA EQUAL TO
≝   (U+225D)  EQUAL TO BY DEFINITION
≞   (U+225E)  MEASURED BY
≟   (U+225F)  QUESTIONED EQUAL TO
≠   (U+2260)  NOT EQUAL TO
≡   (U+2261)  IDENTICAL TO
≢   (U+2262)  NOT IDENTICAL TO
≣   (U+2263)  STRICTLY EQUIVALENT TO
≤   (U+2264)  LESS-THAN OR EQUAL TO
≥   (U+2265)  GREATER-THAN OR EQUAL TO
≦   (U+2266)  LESS-THAN OVER EQUAL TO
≧   (U+2267)  GREATER-THAN OVER EQUAL TO
≨   (U+2268)  LESS-THAN BUT NOT EQUAL TO
≩   (U+2269)  GREATER-THAN BUT NOT EQUAL TO
≪   (U+226A)  MUCH LESS-THAN
≫   (U+226B)  MUCH GREATER-THAN
≬   (U+226C)  BETWEEN
≭   (U+226D)  NOT EQUIVALENT TO
≮   (U+226E)  NOT LESS-THAN
≯   (U+226F)  NOT GREATER-THAN
≰   (U+2270)  NEITHER LESS-THAN NOR EQUAL TO
≱   (U+2271)  NEITHER GREATER-THAN NOR EQUAL TO
≲   (U+2272)  LESS-THAN OR EQUIVALENT TO
≳   (U+2273)  GREATER-THAN OR EQUIVALENT TO
≴   (U+2274)  NEITHER LESS-THAN NOR EQUIVALENT TO
≵   (U+2275)  NEITHER GREATER-THAN NOR EQUIVALENT TO
≶   (U+2276)  LESS-THAN OR GREATER-THAN
≷   (U+2277)  GREATER-THAN OR LESS-THAN
≸   (U+2278)  NEITHER LESS-THAN NOR GREATER-THAN
≹   (U+2279)  NEITHER GREATER-THAN NOR LESS-THAN
≺   (U+227A)  PRECEDES
≻   (U+227B)  SUCCEEDS
≼   (U+227C)  PRECEDES OR EQUAL TO
≽   (U+227D)  SUCCEEDS OR EQUAL TO
≾   (U+227E)  PRECEDES OR EQUIVALENT TO
≿   (U+227F)  SUCCEEDS OR EQUIVALENT TO
⊀   (U+2280)  DOES NOT PRECEDE
⊁   (U+2281)  DOES NOT SUCCEED
⊂   (U+2282)  SUBSET OF
⊃   (U+2283)  SUPERSET OF
⊄   (U+2284)  NOT A SUBSET OF
⊅   (U+2285)  NOT A SUPERSET OF
⊆   (U+2286)  SUBSET OF OR EQUAL TO
⊇   (U+2287)  SUPERSET OF OR EQUAL TO
⊈   (U+2288)  NEITHER A SUBSET OF NOR EQUAL TO
⊉   (U+2289)  NEITHER A SUPERSET OF NOR EQUAL TO
⊊   (U+228A)  SUBSET OF WITH NOT EQUAL TO
⊋   (U+228B)  SUPERSET OF WITH NOT EQUAL TO
⊌   (U+228C)  MULTISET
⊍   (U+228D)  MULTISET MULTIPLICATION
⊎   (U+228E)  MULTISET UNION
⊏   (U+228F)  SQUARE IMAGE OF
⊐   (U+2290)  SQUARE ORIGINAL OF
⊑   (U+2291)  SQUARE IMAGE OF OR EQUAL TO
⊒   (U+2292)  SQUARE ORIGINAL OF OR EQUAL TO
⊓   (U+2293)  SQUARE CAP
⊔   (U+2294)  SQUARE CUP
⊕   (U+2295)  CIRCLED PLUS
⊖   (U+2296)  CIRCLED MINUS
⊗   (U+2297)  CIRCLED TIMES
⊘   (U+2298)  CIRCLED DIVISION SLASH
⊙   (U+2299)  CIRCLED DOT OPERATOR
⊚   (U+229A)  CIRCLED RING OPERATOR
⊛   (U+229B)  CIRCLED ASTERISK OPERATOR
⊜   (U+229C)  CIRCLED EQUALS
⊝   (U+229D)  CIRCLED DASH
⊞   (U+229E)  SQUARED PLUS
⊟   (U+229F)  SQUARED MINUS
⊠   (U+22A0)  SQUARED TIMES
⊡   (U+22A1)  SQUARED DOT OPERATOR
⊢   (U+22A2)  RIGHT TACK
⊣   (U+22A3)  LEFT TACK
⊤   (U+22A4)  DOWN TACK
⊥   (U+22A5)  UP TACK
⊦   (U+22A6)  ASSERTION
⊧   (U+22A7)  MODELS
⊨   (U+22A8)  TRUE
⊩   (U+22A9)  FORCES
⊪   (U+22AA)  TRIPLE VERTICAL BAR RIGHT TURNSTILE
⊫   (U+22AB)  DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
⊬   (U+22AC)  DOES NOT PROVE
⊭   (U+22AD)  NOT TRUE
⊮   (U+22AE)  DOES NOT FORCE
⊯   (U+22AF)  NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
⊰   (U+22B0)  PRECEDES UNDER RELATION
⊱   (U+22B1)  SUCCEEDS UNDER RELATION
⊲   (U+22B2)  NORMAL SUBGROUP OF
⊳   (U+22B3)  CONTAINS AS NORMAL SUBGROUP
⊴   (U+22B4)  NORMAL SUBGROUP OF OR EQUAL TO
⊵   (U+22B5)  CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
⊶   (U+22B6)  ORIGINAL OF
⊷   (U+22B7)  IMAGE OF
⊸   (U+22B8)  MULTIMAP
⊹   (U+22B9)  HERMITIAN CONJUGATE MATRIX
⊺   (U+22BA)  INTERCALATE
⊻   (U+22BB)  XOR
⊼   (U+22BC)  NAND
⊽   (U+22BD)  NOR
⊾   (U+22BE)  RIGHT ANGLE WITH ARC
⊿   (U+22BF)  RIGHT TRIANGLE
⋀   (U+22C0)  N-ARY LOGICAL AND
⋁   (U+22C1)  N-ARY LOGICAL OR
⋂   (U+22C2)  N-ARY INTERSECTION
⋃   (U+22C3)  N-ARY UNION
⋄   (U+22C4)  DIAMOND OPERATOR
⋅   (U+22C5)  DOT OPERATOR
⋆   (U+22C6)  STAR OPERATOR
⋇   (U+22C7)  DIVISION TIMES
⋈   (U+22C8)  BOWTIE
⋉   (U+22C9)  LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
⋊   (U+22CA)  RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
⋋   (U+22CB)  LEFT SEMIDIRECT PRODUCT
⋌   (U+22CC)  RIGHT SEMIDIRECT PRODUCT
⋍   (U+22CD)  REVERSED TILDE EQUALS
⋎   (U+22CE)  CURLY LOGICAL OR
⋏   (U+22CF)  CURLY LOGICAL AND
⋐   (U+22D0)  DOUBLE SUBSET
⋑   (U+22D1)  DOUBLE SUPERSET
⋒   (U+22D2)  DOUBLE INTERSECTION
⋓   (U+22D3)  DOUBLE UNION
⋔   (U+22D4)  PITCHFORK
⋕   (U+22D5)  EQUAL AND PARALLEL TO
⋖   (U+22D6)  LESS-THAN WITH DOT
⋗   (U+22D7)  GREATER-THAN WITH DOT
⋘   (U+22D8)  VERY MUCH LESS-THAN
⋙   (U+22D9)  VERY MUCH GREATER-THAN
⋚   (U+22DA)  LESS-THAN EQUAL TO OR GREATER-THAN
⋛   (U+22DB)  GREATER-THAN EQUAL TO OR LESS-THAN
⋜   (U+22DC)  EQUAL TO OR LESS-THAN
⋝   (U+22DD)  EQUAL TO OR GREATER-THAN
⋞   (U+22DE)  EQUAL TO OR PRECEDES
⋟   (U+22DF)  EQUAL TO OR SUCCEEDS
⋠   (U+22E0)  DOES NOT PRECEDE OR EQUAL
⋡   (U+22E1)  DOES NOT SUCCEED OR EQUAL
⋢   (U+22E2)  NOT SQUARE IMAGE OF OR EQUAL TO
⋣   (U+22E3)  NOT SQUARE ORIGINAL OF OR EQUAL TO
⋤   (U+22E4)  SQUARE IMAGE OF OR NOT EQUAL TO
⋥   (U+22E5)  SQUARE ORIGINAL OF OR NOT EQUAL TO
⋦   (U+22E6)  LESS-THAN BUT NOT EQUIVALENT TO
⋧   (U+22E7)  GREATER-THAN BUT NOT EQUIVALENT TO
⋨   (U+22E8)  PRECEDES BUT NOT EQUIVALENT TO
⋩   (U+22E9)  SUCCEEDS BUT NOT EQUIVALENT TO
⋪   (U+22EA)  NOT NORMAL SUBGROUP OF
⋫   (U+22EB)  DOES NOT CONTAIN AS NORMAL SUBGROUP
⋬   (U+22EC)  NOT NORMAL SUBGROUP OF OR EQUAL TO
⋭   (U+22ED)  DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
⋮   (U+22EE)  VERTICAL ELLIPSIS
⋯   (U+22EF)  MIDLINE HORIZONTAL ELLIPSIS
⋰   (U+22F0)  UP RIGHT DIAGONAL ELLIPSIS
⋱   (U+22F1)  DOWN RIGHT DIAGONAL ELLIPSIS
⋲   (U+22F2)  ELEMENT OF WITH LONG HORIZONTAL STROKE
⋳   (U+22F3)  ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋴   (U+22F4)  SMALL ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋵   (U+22F5)  ELEMENT OF WITH DOT ABOVE
⋶   (U+22F6)  ELEMENT OF WITH OVERBAR
⋷   (U+22F7)  SMALL ELEMENT OF WITH OVERBAR
⋸   (U+22F8)  ELEMENT OF WITH UNDERBAR
⋹   (U+22F9)  ELEMENT OF WITH TWO HORIZONTAL STROKES
⋺   (U+22FA)  CONTAINS WITH LONG HORIZONTAL STROKE
⋻   (U+22FB)  CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋼   (U+22FC)  SMALL CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
⋽   (U+22FD)  CONTAINS WITH OVERBAR
⋾   (U+22FE)  SMALL CONTAINS WITH OVERBAR
⋿   (U+22FF)  Z NOTATION BAG MEMBERSHIP
EOF
)

choice=$(printf '%s\n' "$entries" | \
    dmenu -i -l 18 -p 'Select: ' -fn "${DMENU_FONT:-monospace-12}") || exit 0

[ -n "$choice" ] || exit 0

symbol="${choice%%$'\t'*}"

copy_clipboard() {
    local value=$1

    if command -v wl-copy >/dev/null 2>&1 && [ -n "${WAYLAND_DISPLAY:-}" ]; then
        printf '%s' "$value" | wl-copy
    elif command -v xclip >/dev/null 2>&1 && [ -n "${DISPLAY:-}" ]; then
        printf '%s' "$value" | xclip -selection clipboard
    elif command -v xsel >/dev/null 2>&1 && [ -n "${DISPLAY:-}" ]; then
        printf '%s' "$value" | xsel --clipboard --input
    else
        echo "Error: no clipboard tool found (wl-copy, xclip, or xsel)." >&2
        exit 1
    fi
}

copy_clipboard "$symbol"
